---
- hosts: localhost
  gather_facts: no
  vars:
    state: present
  tasks:
  # Example of role with custom trust policy for Lambda service
  - name: Create IAM role with custom trust relationship
    iam:
      iam_type: role
      name: AAALambdaTestRole
      state: present
      trust_policy:
        Version: '2012-10-17'
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
